version: '3.9'

services:
  db:
    image: postgres:15
    container_name: pg-subscription
    environment:
      POSTGRES_USER: subscription_user
      POSTGRES_PASSWORD: change123
      POSTGRES_DB: subscription_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - subscription-net
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "subscription_user", "-d", "subscription_db"]
        interval: 10s
        timeout: 5s
        retries: 5

  consumer:
    build:
      context: .
      dockerfile: Subscription.Consumer/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=subscription_db;Username=subscription_user;Password=change123
    networks:
      - subscription-net

volumes:
  pgdata:

networks:
  subscription-net:
